services:
  utils_service:
    build: .
    container_name: utils_service
    volumes:
      # Mounts the local ./data folder to /projects in the container
      - ./data:/projects
      # Mount the service account key
      - ./service-account-key.json:/key/service-account-key.json
    environment:
      # Tell Google's libraries where to find the key
      - GOOGLE_APPLICATION_CREDENTIALS=/key/service-account-key.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Keep the container running in the background
    tty: true
    stdin_open: true
    command: sleep infinity

  tensorboard:
    image: tensorflow/tensorflow
    container_name: tensorboard_service
    volumes:
      # Mount the same project folder
      - ./data:/projects
    ports:
      # Expose the TensorBoard web interface on port 6006
      - "6006:6006"
    command: tensorboard --logdir /projects/tensorboard_logs --bind_all
